name: CI/CD

on:
    push:
        branches:
            - main
            - beta
    pull_request:
        branches:
            - main
            - beta

env:
    CI: true

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x

            - run: npm install

            - run: npm run build

            - run: npm run lint

            - run: cp LICENSE package.json README.md build

            - uses: actions/upload-artifact@v3
              with:
                  name: release
                  path: build/

    release:
        runs-on: ubuntu-latest
        needs:
            - test
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta'
        steps:
            - uses: actions/checkout@v4
              with:
                  # Pulls all commits and tags (needed for semantic release to correctly version)
                  fetch-depth: 0
                  persist-credentials: false
                  sparse-checkout: |
                      README.md

            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x

            - run: npm install

            - name: Download release artifact
              uses: actions/download-artifact@v3
              with:
                  name: release
                  path: release

            - name: Release 🚀
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: npx semantic-release@^22
              working-directory: ./release
